[2023-05-31T13:06:15.922+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: time_task.create_table manual__2023-05-31T13:06:14.944802+00:00 [queued]>
[2023-05-31T13:06:15.929+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: time_task.create_table manual__2023-05-31T13:06:14.944802+00:00 [queued]>
[2023-05-31T13:06:15.930+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T13:06:15.931+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-31T13:06:15.931+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T13:06:15.940+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-31 13:06:14.944802+00:00
[2023-05-31T13:06:15.945+0000] {standard_task_runner.py:55} INFO - Started process 223 to run task
[2023-05-31T13:06:15.948+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'time_task', 'create_table', 'manual__2023-05-31T13:06:14.944802+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/insertTime.py', '--cfg-path', '/tmp/tmpbgwj93xp']
[2023-05-31T13:06:15.950+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_table
[2023-05-31T13:06:15.999+0000] {task_command.py:389} INFO - Running <TaskInstance: time_task.create_table manual__2023-05-31T13:06:14.944802+00:00 [running]> on host b61c8577f382
[2023-05-31T13:06:16.056+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=time_task
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T13:06:14.944802+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T13:06:14.944802+00:00
[2023-05-31T13:06:16.057+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS myTime (
                curr_time TIMESTAMP
            );
        
[2023-05-31T13:06:16.065+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-31T13:06:16.172+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-31T13:06:16.174+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

[2023-05-31T13:06:16.181+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=time_task, task_id=create_table, execution_date=20230531T130614, start_date=20230531T130615, end_date=20230531T130616
[2023-05-31T13:06:16.188+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_table (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
; 223)
[2023-05-31T13:06:16.201+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-31T13:06:16.219+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
