[2023-05-31T13:06:13.605+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: time_task.create_table scheduled__2023-05-30T00:00:00+00:00 [queued]>
[2023-05-31T13:06:13.611+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: time_task.create_table scheduled__2023-05-30T00:00:00+00:00 [queued]>
[2023-05-31T13:06:13.611+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T13:06:13.612+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-31T13:06:13.612+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T13:06:13.621+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-30 00:00:00+00:00
[2023-05-31T13:06:13.626+0000] {standard_task_runner.py:55} INFO - Started process 221 to run task
[2023-05-31T13:06:13.629+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'time_task', 'create_table', 'scheduled__2023-05-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/insertTime.py', '--cfg-path', '/tmp/tmpto4vbsyh']
[2023-05-31T13:06:13.630+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_table
[2023-05-31T13:06:13.682+0000] {task_command.py:389} INFO - Running <TaskInstance: time_task.create_table scheduled__2023-05-30T00:00:00+00:00 [running]> on host b61c8577f382
[2023-05-31T13:06:13.730+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=time_task
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-30T00:00:00+00:00
[2023-05-31T13:06:13.731+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS myTime (
                curr_time TIMESTAMP
            );
        
[2023-05-31T13:06:13.739+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-31T13:06:13.860+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-31T13:06:13.861+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

[2023-05-31T13:06:13.869+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=time_task, task_id=create_table, execution_date=20230530T000000, start_date=20230531T130613, end_date=20230531T130613
[2023-05-31T13:06:13.876+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_table (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
; 221)
[2023-05-31T13:06:13.925+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-31T13:06:13.944+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
